### PR TITLE
Fix fatalerror default

### LINKED ISSUE #148: @DependencyEndpoint & Never returning closure
### Description

When applying `@DependencyEndpoint` to a function which return a non-optional type one must provide a closure. While this moved some runtime checks to compile time checks it's not always possible to provide a sensible value or even a value at all.
One can avoid providing a value using `fatalError()` but the macro then emits invalid swift code.

### Checklist

- [X] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-dependencies/issues) or [discussion](https://github.com/pointfreeco/swift-dependencies/discussions).

### Expected behavior

The macro should emit valid swift code even when using `fatalError()` but I think there should be an option to specify the behaviour of the macro so one can skip writing the fatalError entirely

### Actual behavior

_No response_

### Steps to reproduce

```
@DependencyEndpoint
public var fetchCategoryIds: () async throws -> Set<Article.Category.ID> = { fatalError() }
  private var _fetchCategoryIds: () async throws -> Set<Article.Category.ID> = {
      XCTestDynamicOverlay.XCTFail("Unimplemented: 'fetchCategoryIds'")
      return fatalError()
  }
{
    @storageRestrictions(initializes: _fetchCategoryIds)
    init(initialValue) {
        _fetchCategoryIds = initialValue
    }
    get {
        _fetchCategoryIds
    }
    set {
        _fetchCategoryIds = newValue
    }
}
```

### Dependencies version information

1.1.1

### Destination operating system

_No response_

### Xcode version information

_No response_

### Swift Compiler version information

_No response_

### PR DESCRIPTION
**Pull request by mbrandonw**
Fixes #148.

We don't recommend people use `fatalError`'s in their defaults, but we might as well generate valid Swift code if someone has a good reason to.

### CODE REVIEW

File: Sources/DependenciesMacros/Macros.swift [hunk 1]
```diff
@@ -164,3 +164,10 @@ public struct Unimplemented: Error {
     self.endpoint = endpoint
   }
 }
+
+struct Blah {
+  @DependencyEndpoint
+  public var foo: () -> String = { fatalError() }
+  @DependencyEndpoint
+  public var bar: () -> String = { fatalError("Goodbye") }
+}
```
Comment (stephencelis) [inline Sources/DependenciesMacros/Macros.swift:173]:
```suggestion
```

File: Tests/DependenciesMacrosPluginTests/DependencyClientMacroTests.swift [hunk 2]
```diff
@@ -513,22 +513,6 @@ final class DependencyClientMacroTests: BaseTestCase {
...
-        init(
-          endpoint: @Sendable @escaping () -> Int
-        ) {
-          self.endpoint = endpoint
-        }
-
-        init() {
-        }
-      }
-      """
```
Comment (mbrandonw) [inline Tests/DependenciesMacrosPluginTests/DependencyClientMacroTests.swift:531]: this was failing for me and so I had remove it. but not really sure why it doesn't fail on main

**Review by stephencelis — APPROVED** [review]
